// Writes the "What Cadence does" block in README.md from src/lib/catalog.ts, like the ERD in
// ARCHITECTURE.md. `--check` fails if the README is out of date (CI runs it).
import { readFileSync, writeFileSync } from "node:fs";
import { ADJUSTMENTS, COMING, COUNTS, ROUTINES, SETUP, WEEKLY } from "../src/lib/catalog";

const BEGIN = "<!-- CATALOG:BEGIN (generated by scripts/catalog.ts from src/lib/catalog.ts) -->";
const END = "<!-- CATALOG:END -->";
const table = (rows: { name: string; what: string; when?: string }[], when = false) => [
  when ? "| # | Routine | When | What it does |" : "| # | Setting | What it's for |",
  when ? "|---|---|---|---|" : "|---|---|---|",
  ...rows.map((r, i) => when ? `| ${i + 1} | **${r.name}** | ${r.when} | ${r.what} |` : `| ${i + 1} | **${r.name}** | ${r.what} |`),
].join("\n");

const block = [
  BEGIN,
  `**${COUNTS.setup}** settings you choose once · **${COUNTS.weekly}** things you do each week · **${COUNTS.routines}** routines that run for you`,
  "",
  `### Set once (${COUNTS.setup})`, "", table(SETUP), "",
  `### Every week, about two minutes (${COUNTS.weekly})`, "", table(WEEKLY), "",
  `### Runs for you (${COUNTS.routines})`, "", table(ROUTINES, true), "",
  "### How a draft gets adjusted", "",
  "| Outcome | When |", "|---|---|",
  ...ADJUSTMENTS.map((a) => `| **${a.label}** | ${a.items.join("; ")} |`), "",
  `**Coming:** ${COMING.map((c) => `${c.name}: ${c.what}`).join(" ")}`,
  END,
].join("\n");

const readme = readFileSync("README.md", "utf8");
const a = readme.indexOf(BEGIN.slice(0, 20)), b = readme.indexOf(END);
if (a < 0 || b < 0) throw new Error("README.md has no CATALOG markers");
const next = readme.slice(0, a) + block + readme.slice(b + END.length);
if (process.argv.includes("--check")) {
  if (next !== readme) { console.error("README.md catalog block is stale. Run `pnpm catalog`."); process.exit(1); }
  console.log("README catalog block is current.");
} else { writeFileSync("README.md", next); console.log("README catalog block written."); }
