#!/usr/bin/env node
// Generates the ERD block in ARCHITECTURE.md from the latest drizzle-kit snapshot: every table and
// every foreign key, never drawn by hand. `pnpm arch` rewrites it; CI fails if it is stale.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const dir = "drizzle/meta";
const snap = readdirSync(dir).filter((f) => f.endsWith("_snapshot.json")).sort().at(-1);
const { tables } = JSON.parse(readFileSync(`${dir}/${snap}`, "utf8"));
const lines = ["erDiagram"];
for (const t of Object.values(tables)) {
  const cols = Object.values(t.columns).map((c) => `    ${String(c.type).replace(/[^a-zA-Z0-9_]/g, "_")} ${c.name}${c.primaryKey ? " PK" : ""}`);
  lines.push(`  ${t.name} {`, ...cols, "  }");
}
for (const t of Object.values(tables)) for (const fk of Object.values(t.foreignKeys)) lines.push(`  ${fk.tableTo} ||--o{ ${t.name} : "${fk.columnsFrom.join(",")}"`);
const block = ["<!-- ERD:BEGIN (generated by scripts/erd.mjs) -->", "```mermaid", ...lines, "```", "<!-- ERD:END -->"].join("\n");
const doc = readFileSync("ARCHITECTURE.md", "utf8");
const next = doc.replace(/<!-- ERD:BEGIN[\s\S]*?<!-- ERD:END -->/, block);
if (process.argv.includes("--check")) { if (next !== doc) { console.error("ARCHITECTURE.md ERD is stale: run pnpm arch"); process.exit(1); } console.log("erd: current"); }
else { writeFileSync("ARCHITECTURE.md", next); console.log(`erd: ${Object.keys(tables).length} tables`); }
